apiVersion: v1
kind: Service
metadata:
  name: cloud-app-service
  namespace: cloud-app
  labels:
    app: cloud-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: cloud-app
